### ISSUE TITLE
xcodeproj 5.0 checklist

### ISSUE THREAD

**Issue by pepibumur** [xcbuddy/xcodeproj#3]
## Context 🕵️‍♀️
This issue is a checklist  of things that need to be done before the release 5.0.

### Major changes
- [ ] Automatic reference generation.
- [ ] Better equatable conformance.
- [ ] Convenience API.

### Minor changes.
- [ ] Xcode default values.
- [ ] Default build settings.
- [x] SPM packages. https://github.com/xcbuddy/xcodeproj/pull/1
- [ ] Linux compatibility.
- [ ] Code coverage reports.
- [ ] Guided releases.
